### ISSUE TITLE
Code Refactoring for scPortrait Release

### ISSUE THREAD

**Issue by sophiamaedler** [MannLabs/scPortrait#6]
This is an issue to track major code changes that need to be implemented before we publish the package (this issue focuses not on new features but on cleaning up currently implemented features to make the code base more robust and better maintainable).

- [x] segmentation workflows #7 
- [x] classification workflows #22 
- [x] downsampling/upsampling functions #8 
- [ ] switch to using spatial data for saving intermediate results #40 
- [x] ensure all example datasets work with the new spatial data implementation
- [ ] implementing tests for continuous integration #9 
- [ ] Adopt scverse cookiecutter template #17 
- [ ] implement coding best practices #43 

Furthermore the following features should be implemented:
- [ ] new features #47

**Comment by sophiamaedler** [comment]
closing as outdated information
